### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [ZZiyin/UIE-WD_Code#5]
Thank you for sharing your great code. :smiley_cat: 

Sorry for posting a bunch of issues in a row.

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by ZZiyin** [comment]
Hi,
Thank you for your reminding, the license has been added now.

**Comment by PINTO0309** [comment]
Thanks!
